version: "3"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
    tty: true
  frontend:
    build: ./front-end
    volumes:
      - ./front-end:/usr/src/app
    ports:
      - 3000:3000
    command: ["npm", "run", "start"]
    stdin_open: true
    tty: true
  backend:
    build: ./back-end
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - 9000:9000
    command: ["npm", "run", "start"]
    tty: true
